language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-nightwatch' ]; then cd .. && eval "mv $currentfolder generator-nightwatch" && cd generator-nightwatch; fi

